### ISSUE TITLE
Regexp for matching comments with issue numbers

### ISSUE THREAD

**Issue by jesk** [VladRassokhin/intellij-tasks-navigate#4]
Is there any way to link comments in sourcecodes with issues e.g.:
    # TODO Needs update with #1234

I would like to define a pattern such as #\d+ to match any numbers preceded by a hash.
\d+ would match the id for the associated issue tracker i.e. clicking #1234 would open the issue 1234 in the tracker.

**Comment by victor-homyakov** [comment]
I'm facing the same problem with issue numbers in comment. Any help is greatly appreciated.

**Comment by VladRassokhin** [comment]
Hi,
Sorry, somehow missed notification.
IDEA 15 will come with [fixed issue](https://youtrack.jetbrains.com/issue/IDEA-62743) about hichghlighting some ids in comments as external links. (It's not related to this plugin)
At the same time you could setup tasks server with some url and id pattern, so this ('tasks navigation') plugin would do the same but using tasks servers instead of servers defined in "Settings | Version Control | Issue Navigation"
